fs: Remove scsi/ltpscsi testsuite
This testsuite, which contained user space code and custom runner and
expected to be tested with ssi_debug kernel module, was written for
kernel 2.5.

It did not use LTP API and did not even build due various undefined
references:

ltpscsi/sg_err.c:165:(.text+0x2fa): undefined reference to `fwrite'

Probably not worth of fixing, thus removed.

Signed-off-by: Petr Vorel <pvorel@suse.cz>