keyctl: Vendor struct keyctl_dh_params
Copy struct keyctl_dh_params definition into LTP specific struct
ltp_keyctl_dh_params. (Use struct definition from keyutils.h from
keyutils userspace library, UAPI in kernel keeps also private hidden
from C++ by #ifndef guard which we 1) don't need 2) cannot use nested #ifndef.)

This helps to fix compilation on old kernel < 4.20:

    keyctl25.c:25:11: error: ‘struct keyctl_dh_params’ has no member named ‘priv’

'priv' struct member was added in kernel v4.20 (which we still support)
in commit 2ecefa0a15fd0 ("keys: Fix the use of the C++ keyword "private"
in uapi/linux/keyctl.h")

Vendoring struct helps us to remove autotools check (speedup).

Fixes: ee02118e9f ("lapi/keyctl.h: Add fallback definitions for extended ops")
Reported-by: linuxtestproject.agent@gmail.com
Signed-off-by: Petr Vorel <pvorel@suse.cz>