configure: Fix build on kernel 6.14 headers
We decided in a2300dc0f5 to remove <linux/mount.h> in lapi/mount.h and
use only <sys/mount.h>. But later in 5c5411ea8e we add autotools checks
in configure.ac which use <linux/mount.h> for detection, but kept using
lapi/mount.h. This worked until now, because no toolchain used new
header enough. Recent Alpine update broke that.

This fixes CI build on Alpine v3.22 (the default Alpine version in
GitHub action), which uses 6.14.2 kernel headers, which already define
struct mnt_id_req (configure.ac detect it but lapi/mount.h was not using
a correct header):

    listmount.h: In function 'listmount':
    listmount.h:18:16: error: variable 'req' has initializer but incomplete type
       18 |         struct mnt_id_req req = {
	  |                ^~~~~~~~~~

Fixes: 5c5411ea8e ("Add listmount/statmount fallback declarations")
Signed-off-by: Petr Vorel <pvorel@suse.cz>