recvmmsg01: Fix compilation
void* cannot be directly used, it must be pointing to the struct.

recvmmsg01.c:86:9: error: request for member ‘type’ in something not a
structure or union
  timeout.type = tv->ts_type;

Fixes: 135af8ede ("syscalls/{send|recv}mmsg: add a test case for timeout
and errno test")

Reported-by: Li Wang <liwang@redhat.com>
Signed-off-by: Petr Vorel <pvorel@suse.cz>