fsmount.h: Try to fix mount includes
In file included from fsconfig01.c:9:
../../../../include/lapi/fsmount.h:55:8: error: redefinition of 'struct mount_attr'
   55 | struct mount_attr {
      |        ^~~~~~~~~~
In file included from ../../../../include/lapi/fsmount.h:14:
/home/autobuild/autobuild/instance-4/output-1/host/armeb-buildroot-linux-gnueabi/sysroot/usr/include/sys/mount.h:210:8: note: originally defined here
  210 | struct mount_attr
      |        ^~~~~

Link: http://autobuild.buildroot.org/results/4dbb72e1bf081afd3cd944571b9beeefc7608865
Fixes: b857f8723 ("lapi/fsmount: resolve conflict in different header files")
Reported-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Petr Vorel <pvorel@suse.cz>