lapi: Introduce {linux,sys}_mount.h to fix MUSL on 6.14 headers
Due indirect include <linux/mount.h> by <linux/fs.h> we really need to
separate old and new mount API. This fixes error:

This fixes CI build on Alpine v3.22 (the default Alpine version in
GitHub action), which uses 6.14.2 kernel headers:

In file included from /usr/include/linux/fs.h:19,
                 from /usr/include/linux/btrfs.h:29,
                 from statmount02.c:23:
/usr/include/linux/mount.h:155:8: error: redefinition of 'struct statmount'
  155 | struct statmount {
      |        ^~~~~~~~~
In file included from statmount.h:12,
                 from statmount02.c:20:
../../../../include/lapi/mount.h:58:8: note: originally defined here
   58 | struct statmount {
      |        ^~~~~~~~~
/usr/include/linux/mount.h:193:8: error: redefinition of 'struct mnt_id_req'
  193 | struct mnt_id_req {
      |        ^~~~~~~~~~
../../../../include/lapi/mount.h:49:8: note: originally defined here
   49 | struct mnt_id_req {
      |        ^~~~~~~~~~

But we still support old Leap 42 (glibc 2.22 based), which requires for
statmount04.c old fallbacks for <sys/mount.h> but also new mount API
defined in <linux/mount.h>, otherwise it fails:

statmount03.c:62:4: error: 'MS_PRIVATE' undeclared here (not in a function)
  { MS_PRIVATE, TST_TO_STR_(MS_PRIVATE) },
    ^
statmount03.c:63:4: error: 'MS_SHARED' undeclared here (not in a function)
  { MS_SHARED, TST_TO_STR_(MS_SHARED) },
    ^
statmount03.c:64:4: error: 'MS_SLAVE' undeclared here (not in a function)
  { MS_SLAVE, TST_TO_STR_(MS_SLAVE) },
    ^
In file included from ../../../../include/tst_test.h:185:0,
                 from statmount.h:11,
                 from statmount04.c:21:
statmount04.c: In function 'setup':
statmount03.c:65:4: error: 'MS_UNBINDABLE' undeclared here (not in a function)
  { MS_UNBINDABLE, TST_TO_STR_(MS_UNBINDABLE) },
    ^
statmount04.c:57:35: error: 'MS_BIND' undeclared (first use in this function)
  SAFE_MOUNT(DIR_A, DIR_A, "none", MS_BIND, NULL);
                                   ^
../../../../include/tst_safe_macros.h:244:25: note: in definition of macro 'SAFE_MOUNT'
      (filesystemtype), (mountflags), (data))
                         ^
In file included from ../../../../include/tst_test.h:185:0,
                 from statmount.h:11,
                 from statmount03.c:21:
statmount03.c: In function 'run':
statmount04.c:57:35: note: each undeclared identifier is reported only once for each function it appears in
  SAFE_MOUNT(DIR_A, DIR_A, "none", MS_BIND, NULL);
                                   ^
../../../../include/tst_safe_macros.h:244:25: note: in definition of macro 'SAFE_MOUNT'
      (filesystemtype), (mountflags), (data))
                         ^
statmount03.c:74:35: error: 'MS_BIND' undeclared (first use in this function)
  SAFE_MOUNT(DIR_B, DIR_A, "none", MS_BIND, NULL);

Fixes: 5c5411ea8e ("Add listmount/statmount fallback declarations")
Fixes: 3ef4bac1dd ("configure: Fix build on kernel 6.14 headers")
Signed-off-by: Petr Vorel <pvorel@suse.cz>