lapi/fs: Include lapi/fcntl.h + define _GNU_SOURCE
Add required _GNU_SOURCE definition in lapi/fs.h to get loff_t
definition. This fixes build error on musl (alpine):

    In file included from unlink09.c:18:
    ../../../../include/lapi/fs.h:58:15: error: unknown type name 'loff_t'
       58 | static inline loff_t tst_max_lfs_filesize(void)

loff_t is defined in <fcntl.h> (but guarded _GNU_SOURCE), but just for
safety include lapi/fcntl.h in case lapi/fs.h is included in test which
needs fallback definitions from lapi/fcntl.h.

Also, instead adding _GNU_SOURCE to unlink09.c just include lapi/fs.h
after tst_test.h. But reverting the order requires also add <unistd.h>
to lapi/fcntl.h to fix missing getpagesize() on 32 bit build:

    In file included from unlink09.c:17:
    ../../../../include/lapi/fs.h: In function 'tst_max_lfs_filesize':
    ../../../../include/lapi/fs.h:66:26: error: implicit declaration of function 'getpagesize' [-Werror=implicit-function-declaration]
       66 |         long page_size = getpagesize();
	  |                          ^~~~~~~~~~~

(For some reason <unistd.h> is not required on 64 bit build.)
getpagesize() is also guarded _GNU_SOURCE.

Obviously having functions in lapi headers (or any headers) which
depends on _GNU_SOURCE brings problems. But moving
tst_max_lfs_filesize() out of lapi to lib/tst_*.c would not help either,
because here is loff_t also in the function signature which we need to
API header, which would again need _GNU_SOURCE definition.

Fixes: 2cf78f47a ("unlink: Add error tests for EPERM and EROFS")
Signed-off-by: Petr Vorel <pvorel@suse.cz>