lapi/ip_tables.h: Includes netinet/in.h
Alternative fix for failing setsockopt08 (fixed in 2c4c2d8f7).

We have to put netinet/in.h on the top to get rid of conflict
of glibc and kernel headers for old Ubuntu.

/usr/include/linux/in.h:28:3: error: redeclaration of enumerator 'IPPROTO_IP'
    IPPROTO_IP = 0,  /* Dummy protocol for TCP  */
^
/usr/include/netinet/in.h:42:5: note: previous definition of 'IPPROTO_IP' was here
   IPPROTO_IP = 0,    /* Dummy protocol for TCP.  */
...

See: https://www.mail-archive.com/netdev@vger.kernel.org/msg132711.html

Signed-off-by: Petr Vorel <pvorel@suse.cz>