Define SYS_futex on 32bit arches using 64-bit time_t
Newer 32bit arches like RISCV32 and ARC are using 64bit time_t
from get go unlike other 32bit architecture therefore aliasing __NR_futex to
__NR_futex_time64 helps avoid the below errors

tst_checkpoint.c:99:17: error: use of undeclared identifier 'SYS_futex'

Signed-off-by: Khem Raj <raj.khem@gmail.com>
[ moved definitions to lapi/futex.h ]
Signed-off-by: Petr Vorel <petr.vorel@gmail.com>