keyctl: Use struct keyctl_dh_params 'private' instead of 'priv'
Move struct keyctl_dh_params 'priv' member to union, together with newly
added 'private' member. This is similar what UAPI does since kernel 4.20
commit 2ecefa0a15fd0 ("keys: Fix the use of the C++ keyword "private"
in uapi/linux/keyctl.h"), which adds private member in union in struct
keyctl_dh_params in <linux/keyctl.h>:

    struct keyctl_dh_params {
	    union {
    #ifndef __cplusplus
		    __s32 private;
    #endif
		    __s32 priv;
	    };
	    __s32 prime;
	    __s32 base;
    };

This allows to unconditionally use 'private' member in keyctl tests
which fixes compilation on old kernel < 4.20:

    keyctl25.c:25:11: error: ‘struct keyctl_dh_params’ has no member named ‘priv’

Fixes: ee02118e9f ("lapi/keyctl.h: Add fallback definitions for extended ops")
Suggested-by: Cyril Hrubis <chrubis@suse.cz>
Signed-off-by: Petr Vorel <pvorel@suse.cz>