tools/kirk: Update to fix symlink for rpm packaging
Update kirk to 61591a1 to fix failure during rpm packaging:
ERROR: Link /opt/ltp/runltp-ng ->
/home/abuild/rpmbuild/BUILDROOT/ltp-20230929.48a150bf-1573.1.x86_64/opt/ltp/kirk
points inside build root

Signed-off-by: Petr Vorel <pvorel@suse.cz>