sched_stress: Use time_t instead of long for type
This ensures it works across different architectures
Fixes

| sched_driver.c:744:43: error: passing argument 1 of 'ctime' from incompatible pointer type [-Wincompatible-pointer-types]
|   744 |         printf("\nend time = %s\n", ctime(&end_time));
|       |                                           ^~~~~~~~~

With gcc-14

Signed-off-by: Khem Raj <raj.khem@gmail.com>