configure: Fix struct mnt_id_req and statmount detection
Although these detections are atm defined only in <linux/mount.h>
and not yet in <sys/mount.h>. But lapi/mount.h which adds the fallback
definitions includes only <sys/mount.h> due <sys/mount.h> vs.
<linux/mount.h> conflict. Therefore content of <sys/mount.h> must be
check by autotools.

This fixes build on musl (on yocto configuration, for some reason it
works on Alpine in LTP CI), reported by Richard:

| In file included from listmount01.c:22:
| listmount.h: In function 'listmount':
| listmount.h:18:16: error: variable 'req' has initializer but incomplete type
|    18 |         struct mnt_id_req req = {
|       |                ^~~~~~~~~~
| listmount.h:19:18: error: 'struct mnt_id_req' has no member named 'size'
|    19 |                 .size = MNT_ID_REQ_SIZE_VER0,
|       |                  ^~~~

Because glibc since 2.37 includes <linux/mount.h> in <sys/mount.h> if
available, it probably fixes build on glibc without kernel headers.

Fixes: 5c5411ea8e ("Add listmount/statmount fallback declarations")
Reported-by: Richard Purdie <richard.purdie@linuxfoundation.org>
Signed-off-by: Petr Vorel <petr.vorel@gmail.com>