ci: Don't test generation on Debian oldstable
html generation with asciidoc is broken on Debian 11 bullseye
(the new Debian oldstable):

a2x: ERROR: "xsltproc" --stringparam toc.section.depth 1 --stringparam
callout.graphics 0 --stringparam navig.graphics 0 --stringparam
admon.textlabel 1 --stringparam admon.graphics 0 --stringparam
chunk.section.depth 0  --output "/__w/ltp/ltp/docparse/metadata.html"
"/etc/asciidoc/docbook-xsl/xhtml.xsl"
"/__w/ltp/ltp/docparse/metadata.xml" returned non-zero exit status 5

First reason is that docbook2x is needed to get required XSL (broken
dependency, which is fixed on newer Debian versions).

But even with it being installed, it still does not work on GitHub
Actions, due somehow special network, e.g. ping 8.8.8.8 does not work
(firewall?), code working locally fails on CI:

cd metadata && make
error : Unknown IO error
warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/xhtml/docbook.xsl"
compilation error: file /etc/asciidoc/docbook-xsl/xhtml.xsl line 12 element import
xsl:import : unable to load http://docbook.sourceforge.net/release/xsl/current/xhtml/docbook.xsl

Because asciidoc is tested on other distros, simply remove the test.

Reported-by: Li Wang <liwang@redhat.com>
Signed-off-by: Petr Vorel <pvorel@suse.cz>