ci/tumbleweed.sh: Workaround zypper failures
zypper sometimes fails with exit code 104:

File 'repomd.xml' from repository 'Update Repository (Non-Oss)' is unsigned, continue? [yes/no] (no): no
error]
Warning: Skipping repository 'Update Repository (Non-Oss)' because of the above error.
Loading repository data...
Reading installed packages...
[repo-update-non-oss|http://download.opensuse.org/update/leap/15.4/non-oss/] Valid metadata not found at specified URL
History:
 - Signature verification failed for repomd.xml
 - Can't provide /repodata/repomd.xml

No provider of 'perl-JSON' found.
No provider of 'pkg-config' found.
Error: Process completed with exit code 104.

Adding --no-gpg-checks --ignore-unknown should help to not fail.
The build will be without required headers.

Signed-off-by: Petr Vorel <pvorel@suse.cz>