lapi: Add sysinfo.h to fix build with older MUSL toolchain
When building LTP with older MUSL based toolchains without kernel fix
a85cbe6159ff ("uapi: move constants from <linux/kernel.h> to <linux/const.h>")
from 5.11 build fails due indirect <linux/sysinfo.h> include when using
some network headers: <linux/netlink.h> or others -> <linux/kernel.h> ->
<linux/sysinfo.h>. This indirect include causes on MUSL redefinition of
struct sysinfo when included both <sys/sysinfo.h> and some of UAPI headers:

In file included from x86_64-buildroot-linux-musl/sysroot/usr/include/linux/kernel.h:5,
		 from x86_64-buildroot-linux-musl/sysroot/usr/include/linux/netlink.h:5,
		 from ../include/tst_netlink.h:14,
		 from tst_crypto.c:13:
x86_64-buildroot-linux-musl/sysroot/usr/include/linux/sysinfo.h:8:8: error: redefinition of ‘struct sysinfo’
 struct sysinfo {
	^~~~~~~
In file included from ../include/tst_safe_macros.h:15,
		 from ../include/tst_test.h:93,
		 from tst_crypto.c:11:
x86_64-buildroot-linux-musl/sysroot/usr/include/sys/sysinfo.h:10:8: note: originally defined here

a85cbe6159ff was merged into stable versions, but Buildroot projects
reports still older MUSL toolchains not using it. Therefore they asked
to require 5.11 headers for musl, which mean no LTP for many toolchains.

[ upstream status: ]

Signed-off-by: Petr Vorel <petr.vorel@gmail.com>